# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  # - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

# 3. Gem settings
# paginate: 2 # jekyll-paginate > items per page
# paginate_path: blog/page:num # jekyll-paginate > blog page
author: fonssk # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: FONS Slovensko # jekyll-seo-tag > real name
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://www.instagram.com/fonsslovensko/
    - "https://www.facebook.com/FONS.Slovensko/"
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
# options: ["SMART", "FOOTNOTES"]
# extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- více --> # Marks end of excerpt in posts
timezone: Europe/Prague # Timezone for blog posts and alike

# 5. Collections
# collections:
#   posts:
#     title: Posts # Needed for Siteleaf
#     output: true
#     description: "My thoughts and ideas" # The post list page content
#     feature_text: |
#       Welcome to the blog
#     feature_image: "https://picsum.photos/2560/600?image=866"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-SK # Set the site language
title: "FONS Slovensko" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/fons.svg" # Site logo, also used in jekyll-seo-tag
description: "Československý kurz pro skauty i neskauty s bouřlivou historií, který rozšiřuje obzory, testuje hranice a otevírá oči pro nevšední vidění všedních věcí." # Site description and default description, also used in jekyll-seo-tag
url: "https://fons.skauting.sk" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/fonssk/fonssk.github.io"
email: "fons@skauting.sk"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: "/assets/logos/fons@16px.png"
  32: "/assets/logos/fons@32px.png"
  96: "/assets/logos/fons@96px.png"
  120: "/assets/logos/fons@120px.png"
  144: "/assets/logos/fons@144px.png"
  180: "/assets/logos/fons@180px.png"
  512: "/assets/logos/fons@512px.png"
  1024: "/assets/logos/fons@1024px.png"

# 9. Site navigation
navigation_header:
  - title: FONS
    url: /
  - title: Tím
    url: /tim/
  - title: Historie
    url: /historie/
  - title: Jesenné stretnutie
    url: https://fons.skauting.cz/podzimni-setkani
  - title: ""
    url: https://www.facebook.com/pages/FONS-Slovensko/123176574470887
  - title: ""
    url: https://www.instagram.com/fonsslovensko/

navigation_footer:
  - title: "mail: fons{zavinac}scouting.sk"
    url: mailto:?subject=FONS

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Instagram: "https://www.instagram.com/fonsslovensko/"
  Facebook: "https://www.facebook.com/FONS.Slovensko/"

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Instagram: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
#
# TIP: Try to keep the number of urls as low to reduce the performance cost
#      If multiple fonts can be requested in a single url opt for this
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap

remote_theme: daviddarnes/alembic@main
